---
- hosts: "master"
  tasks:
   - name: Install ingress-nginx Charts
     kubernetes.core.helm:
       name: ingress-nginx
       namespace: ingress-nginx
       create_namespace: true
       chart_ref: ingress-nginx/ingress-nginx
       values_files:
         - /home/vmadmin/k8s_labs/5-nginx-ingress/9-nginx-ingress_values.yml
