---
- hosts: "master"
  tasks:
   - name: Install ingress-nginx Charts
     kubernetes.core.helm:
       name: ingress-nginx
       namespace: ingress-nginx
       create_namespace: true
       chart_ref: ingress-nginx/ingress-nginx

