---
- hosts: "master"
  tasks:
   - name: Install Kubed Charts
     kubernetes.core.helm:
       name: kubed
       namespace: kube-system
       create_namespace: true
       chart_ref: kubed/kubed
#       values_files:
#         - /home/vmadmin/helm_ansible/certman_values.yml
