---
- hosts: "master"
  tasks:
   - name: Install NFS Subdir External Provisioner Charts
     kubernetes.core.helm:
       name: nfs-subdir-external-provisioner
       namespace: nfs-provisioner
       create_namespace: true
       chart_ref: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
       values_files:
        - /home/vmadmin/k8s_labs/3-NFS-subdir-external-provisioner/9-dynamic-nfs-provisioner_values.yml
