---
- hosts: "master"
  tasks:
   - name: Install ECK Charts
     kubernetes.core.helm:
       name: eck-operator
       namespace: elastic-system
       create_namespace: true
       chart_ref: eck/eck-operator
       values_files:
         - /home/vmadmin/k8s_labs/12-eck/9-eck-operator_values.yml
