apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic-system
spec:
  version: 8.14.2
  kibanaRef:
    name: kibana
    namespace: elastic-system
  elasticsearchRefs:
  - name: elastic-cluster
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elastic-agent-acc
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
