---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nginx
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-nginx
  nfs:
    path: /export/kubernetes/nginx_main
    server: 192.168.1.99
