---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-nginx
  namespace: default
spec:
  storageClassName: nfs-nginx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-postgres
  namespace: default
spec:
  storageClassName: nfs-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

