---
- hosts: "master"
  tasks:
   - name: Install ECK Charts
     kubernetes.core.helm:
       name: eck-operator
       namespace: elastic-system
       create_namespace: true
       chart_ref: eck/eck-operator
       values_files:
         - /home/vmadmin/helm_ansible/7b-eck-values.yml
