alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - crudevops.zapto.org
    paths:
    - /alertmanager(/|$)(.*)
    tls:
    - secretName: ssl-cert-production
      hosts:
      - crudevops.zapto.org

  alertmanagerSpec:
    externalUrl: https://crudevops.zapto.org/alertmanager
    routePrefix: /
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-dyn-storageclass
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 5Gi

grafana:
  env:
    GF_SERVER_ROOT_URL: https://crudevops.zapto.org/grafana
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - crudevops.zapto.org
    path: /grafana(/|$)(.*)
    tls:
    - secretName: ssl-cert-production
      hosts:
      - crudevops.zapto.org

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - crudevops.zapto.org
    paths:
    - /prometheus
    tls:
    - secretName: ssl-cert-production
      hosts:
      - crudevops.zapto.org

  prometheusSpec:
    externalUrl: "https://crudevops.zapto.org/prometheus"
    routePrefix: "/prometheus"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-dyn-storageclass
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
