alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - example.com
    paths:
    - /alertmanager(/|$)(.*)
    tls:
    - secretName: ssl-cert-production
      hosts:
      - example.com

  alertmanagerSpec:
    externalUrl: https://example.com/alertmanager
    routePrefix: /
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-alertmanager
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
grafana:
  env:
    GF_SERVER_ROOT_URL: https://example.com/grafana
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
    - example.com
    path: /grafana(/|$)(.*)
    tls:
    - secretName: ssl-cert-production
      hosts:
      - example.com

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - example.com
    paths:
    - /prometheus
    tls:
    - secretName: ssl-cert-production
      hosts:
      - example.com

  prometheusSpec:
    externalUrl: "https://example.com/prometheus"
    routePrefix: "/prometheus"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-prometheus
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 5Gi
