alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts: ['example.com']
    paths: ['/alertmanager(/|$)(.*)']
    tls:
    - secretName: ssl-cert-production
      hosts:
      - example.com

  alertmanagerSpec:
    externalUrl: https://example.com/alertmanager
    routePrefix: "/"
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-alertmanager
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  env:
    GF_SERVER_ROOT_URL: https://example.com/grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts: ['example.com']
    path: "/grafana(/|$)(.*)"
    tls:
    - secretName: ssl-cert-production
      hosts:
      - example.com

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts: ['example.com']
    paths: ['/prometheus'] #
    tls:
    - secretName: ssl-cert-production
      hosts:
      - example.com

  prometheusSpec:
    externalUrl: "https://example.com/prometheus"
    routePrefix: /prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-prometheus
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
