---
- hosts: "master"
  tasks:
#   - name: install pre-requisites
#     pip:
#       name:
#         - openshift
#         - pyyaml
#         - kubernetes

   - name: Install cert-manager Charts
     kubernetes.core.helm:
       name: cert-manager
       namespace: cert-manager
       create_namespace: true
       chart_ref: cert-manager/cert-manager
       values_files:
         - /home/vmadmin/k8s_labs/5-cert-manager/9-cert-manager_values.yml
